version: "3"
services:
  jassue-admin:
    # Base image documentation: https://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-nginx.html
    image: jassue/laravel:7.4
    container_name: jassue-admin
    expose:
      - "80"
      - "443"
    ports:
      - "80:80"
      - "443:443"
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
    volumes:
      - ./:/app
      - ./build/laravel.supervisor.conf:/opt/docker/etc/supervisor.d/laravel.conf

networks:
  default:
    driver: bridge
